spring.application.name=barua
server.port=8088
server.address=0.0.0.0
# profile d'éxecution
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.r2dbc.initialization-mode=always
spring.cloud.gcp.project-id=${GCS_PROJECT_ID}
app.api.key=${FLEXPAIE}
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.cloud.gcp.credentials.location=classpath:barua-store.json
# Tomcat-specific properties for maximum post size and swallow size
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
# THYMELEAF PROPERTIES
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.thymeleaf=DEBUG
# GOOGLE CLOUD STORAGE PROPERTIES
gcs.bucket-name=${GCC_BUCKET}
gcs.subdirectory=barua
storage.location=/opt/backend/casa
# JWT PROPERTIES
jwt.secret=${JWT_SECRET_SERVER}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000
# SWAGGER-UI PROPERTIES
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
# pool size PROPERTIES
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-Prod
spring.datasource.hikari.data-source-properties.prepareThreshold=0
# TWILIO PROPERTIES
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
sentry.dsn=${SENTRY_DNS}
# SENTRY PROPERTIES
sentry.send-default-pii=true
sentry.enabled=true
sentry.debug=false
sentry.metrics.enabled=true
sentry.logs.enabled=true
sentry.traces-sample-rate=1.0
# scheduler PROPERTIES
spring.quartz.scheduler.instanceName=reservationScheduler
spring.quartz.scheduler.instanceId=AUTO
# Type de JobStore (persistant)
spring.quartz.job-store-type=jdbc
spring.quartz.job-store.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.job-store.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.job-store.tablePrefix=QRTZ_
spring.quartz.job-store.isClustered=true

# Pool de threads
spring.quartz.threadPool.threadCount=5